var rotas={
    "about": "<div class=\"container\">\n\t<div class=\"row\">\n\t\t<div class=\"col3\"><\/div>\n\t\t<div class=\"col6\">\n\t\t\t<h2 class=\"box\">{{title}}<\/h2>\n\t\t\t<p class=\"box\">\n\t\t\t\tLorem ipsum dolor, sit amet consectetur adipisicing elit. Ut impedit aliquid minus reiciendis atque voluptates, ipsa at inventore nesciunt totam a odio sunt culpa maiores. Praesentium et eius amet odio.\n\t\t\t<\/p>\n\t\t<\/div>\n\t<\/div>\n<\/div>",
    "home": "<script src=\"https:\/\/www.google.com\/recaptcha\/api.js\"><\/script>\n<div class=\"container\">\n\t<div class=\"row\">\n\t\t<div class=\"col3\"><\/div>\n\t\t<div class=\"col6\">\n\t\t\t<form action=\"{{SITE_URL}}\/messages\" class=\"box vertical\" id=\"formMessage\" method=\"post\">\n\t\t\t\t<label for=\"message\">Mensagem:<\/label>\n\t\t\t\t<textarea id=\"message\" name=\"message\" maxlength=\"128\" minlength=\"1\" required><\/textarea>\n\t\t\t\t<button type=\"submit\" class=\"g-recaptcha\" \n        data-sitekey=\"{{RECAPTCHA_PUBLIC_KEY}}\" \n        data-callback='onSubmit' \n        data-action='submit'>Enviar<\/button>\n\t\t\t<\/form>\n\t\t\t<hr>\n\t\t\t<h2 class=\"box\">Mensagens<\/h2>\n\t\t\t{{#messages}}\n\t\t\t<p class=\"box\">\n\t\t\t\t{{message}}\n\t\t\t<\/p>\n\t\t\t<p class=\"box\">\n\t\t\t\t<small>\n\t\t\t\t\t<a href=\"{{link_to}}\" x-spa>\n\t\t\t\t\t\t{{created_at_h}}\n\t\t\t\t\t<\/a>\n\t\t\t\t<\/small>\n\t\t\t<\/p>\n\t\t\t<hr>\n\t\t\t{{\/messages}}\n\t\t<\/div>\n\t<\/div>\n<\/div>",
    "messages": "<div class=\"container\">\n\t<div class=\"row\">\n\t\t<div class=\"col3\"><\/div>\n\t\t<div class=\"col6\">\n\t\t\t{{#message}}\n\t\t\t<p class=\"box\">\n\t\t\t\t{{message}}\n\t\t\t<\/p>\n\t\t\t<p>\n\t\t\t\t<small>{{created_at_h}}<\/small>\n\t\t\t<\/p>\n\t\t\t{{\/message}}\t\n\t\t\t<p>\n\t\t\t\t<a href=\"javascript:history.back();\">\n\t\t\t\t\tVoltar\n\t\t\t\t<\/a>\n\t\t\t<\/p>\n\n\t\t<\/div>\n\t<\/div>\n<\/div>",
    "msg": "<div class=\"container\">\n\t<div class=\"row\">\n\t\t<div class=\"col3\"><\/div>\n\t\t<div class=\"col6\">\n\t\t\t<h2>{{title}}<\/h2>\n\t\t\t<p class=\"box\">\n\t\t\t\t{{msg}}\n\t\t\t<\/p>\n\t\t\t<p>\n\t\t\t\t<a href=\"javascript:history.back();\">\n\t\t\t\t\tVoltar\n\t\t\t\t<\/a>\n\t\t\t<\/p>\n\t\t<\/div>\n\t<\/div>\n<\/div>"
};
var SITE_DOMAIN="http://localhost";
var SITE_NAME="Guest";
var SITE_URL="http://localhost/guest/public";
var SITE_VERSION="0.2.5";
